// <auto-generated />
using FinanceFlix.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FinanceFlix.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceFlix.API.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DESC_CATEGORIA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_CATEGORIA");

                    b.HasKey("Id");

                    b.ToTable("TB_CATEGORIA");
                });

            modelBuilder.Entity("FinanceFlix.API.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DESC_CURSO");

                    b.Property<byte[]>("ImagemUrl")
                        .HasColumnType("RAW(2000)")
                        .HasColumnName("IMG_CURSO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_CURSO");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TB_CURSO");
                });

            modelBuilder.Entity("FinanceFlix.API.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VIDEO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DESC_VIDEO");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DURACAO_VIDEO");

                    b.Property<string>("FilePath")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PATH_VIDEO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_VIDEO");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("URL_VIDEO");

                    b.HasKey("Id");

                    b.ToTable("TB_VIDEO");
                });

            modelBuilder.Entity("FinanceFlix.Domain.Entities.CursoTrilha", b =>
                {
                    b.Property<int>("CursoVideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoVideoId"));

                    b.Property<int>("CursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TrilhaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CursoVideoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("TrilhaId");

                    b.ToTable("TB_CURSO_TRILHA");
                });

            modelBuilder.Entity("FinanceFlix.Domain.Entities.CursoVideo", b =>
                {
                    b.Property<int>("CursoVideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoVideoId"));

                    b.Property<int>("CursoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VideoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CursoVideoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("VideoId");

                    b.ToTable("TB_CURSO_VIDEO");
                });

            modelBuilder.Entity("FinanceFlix.Domain.Entities.Trilha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRILHA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DESC_TRILHA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NOME_TRILHA");

                    b.HasKey("Id");

                    b.ToTable("TB_TRILHA");
                });

            modelBuilder.Entity("FinanceFlix.API.Entities.Curso", b =>
                {
                    b.HasOne("FinanceFlix.API.Entities.Categoria", "Categoria")
                        .WithMany("Cursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FinanceFlix.Domain.Entities.CursoTrilha", b =>
                {
                    b.HasOne("FinanceFlix.API.Entities.Curso", "Curso")
                        .WithMany("CursosTrilhas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceFlix.Domain.Entities.Trilha", "Trilha")
                        .WithMany("CursosTrilhas")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("FinanceFlix.Domain.Entities.CursoVideo", b =>
                {
                    b.HasOne("FinanceFlix.API.Entities.Curso", "Curso")
                        .WithMany("CursosVideos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceFlix.API.Entities.Video", "Video")
                        .WithMany("CursosVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("FinanceFlix.API.Entities.Categoria", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("FinanceFlix.API.Entities.Curso", b =>
                {
                    b.Navigation("CursosTrilhas");

                    b.Navigation("CursosVideos");
                });

            modelBuilder.Entity("FinanceFlix.API.Entities.Video", b =>
                {
                    b.Navigation("CursosVideos");
                });

            modelBuilder.Entity("FinanceFlix.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("CursosTrilhas");
                });
#pragma warning restore 612, 618
        }
    }
}
